"""添加气候和服装设定字段到projects表

Revision ID: b2c3d4e5f6a7
Revises: acdb1d611064
Create Date: 2026-09-18 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = 'acdb1d611064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_climate', sa.Text(), nullable=True, comment='气候设定'))
        batch_op.add_column(sa.Column('world_clothing', sa.Text(), nullable=True, comment='服装设定'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('world_clothing')
        batch_op.drop_column('world_climate')

    # ### end Alembic commands ###
